# Generated by Django 3.1.5 on 2021-01-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='storage_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.company')),
            ],
        ),
        migrations.CreateModel(
            name='type_of_Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Storage_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage_number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.company')),
            ],
        ),
        migrations.CreateModel(
            name='storage_Valid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Storage_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage_number')),
                ('Type_of_Storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.type_of_storage')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.company')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', models.TextField(blank=True, max_length=100)),
                ('Material_Seggregation', models.BooleanField(null=True)),
                ('Barrication_in_Place', models.BooleanField(null=True)),
                ('Seggregation_of_non_Valid_and_Damaged_Tools', models.BooleanField(null=True)),
                ('Housekeeping_issues', models.BooleanField(null=True)),
                ('SDS_in_Place', models.BooleanField(null=True)),
                ('Materials_Stacked_Properly', models.BooleanField(null=True)),
                ('Water_Pounding_on_Floor', models.BooleanField(null=True)),
                ('canvas_cover_Without_Rain_Water', models.BooleanField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Storage_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.storage_number')),
                ('Storage_Valid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.storage_valid')),
                ('Type_of_Storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.type_of_storage')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.company')),
            ],
        ),
    ]
