# Generated by Django 3.1.5 on 2021-01-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='Storage_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.storage_number'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='Storage_Valid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.storage_valid'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='Type_of_Storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.type_of_storage'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.company'),
        ),
    ]
